"""
common/db.py — Aegis Link shared SQLite foundation.

Provides a single get_connection() factory and a bootstrap_schema() call that
every other module imports. WAL journal mode is enabled so Aegis-Brain's
write-heavy processing and Aegis-Bridge's concurrent reads do not deadlock.

Schema
──────
raw_intel      — one row per unique article; url_hash is the canonical
                 dedup key (SHA-256 of the normalised URL).
draft_analysis — human-in-the-loop staging table; YARA rules and TTP
                 mappings wait here for investigator confirmation before
                 being treated as operational intelligence.
"""

import os
import sqlite3
import threading
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# ── Database path ─────────────────────────────────────────────────────────────
_PROJECT_ROOT = Path(__file__).resolve().parents[1]
DB_PATH: str = os.environ.get(
    "AEGIS_DB_PATH",
    str(_PROJECT_ROOT / "aegis_intel.db"),
)

# ── Thread-safety for connection creation ─────────────────────────────────────
_lock = threading.Lock()

# ── DDL — raw_intel ───────────────────────────────────────────────────────────
_RAW_INTEL_DDL = """
CREATE TABLE IF NOT EXISTS raw_intel (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    -- url_hash is a SHA-256 hex digest of the normalised source URL.
    -- It is the canonical idempotency key: INSERT OR IGNORE on this column
    -- guarantees each article is stored exactly once regardless of minor
    -- URL variations (trailing slashes, etc. are normalised before hashing).
    url_hash      TEXT    NOT NULL UNIQUE,
    source_url    TEXT    NOT NULL UNIQUE,
    title         TEXT    NOT NULL,
    pub_date      TEXT,
    raw_text      TEXT,
    stix_json     TEXT,
    processed_at  TEXT,
    is_processed  INTEGER NOT NULL DEFAULT 0
        CHECK (is_processed IN (-1, 0, 1))
);

CREATE INDEX IF NOT EXISTS idx_raw_intel_url_hash
    ON raw_intel (url_hash);

CREATE INDEX IF NOT EXISTS idx_raw_intel_is_processed
    ON raw_intel (is_processed);

CREATE INDEX IF NOT EXISTS idx_raw_intel_pub_date
    ON raw_intel (pub_date);
"""

# ── DDL — draft_analysis (human-in-the-loop) ─────────────────────────────────
_DRAFT_ANALYSIS_DDL = """
CREATE TABLE IF NOT EXISTS draft_analysis (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    raw_intel_id   INTEGER NOT NULL REFERENCES raw_intel(id),
    -- draft_yara holds the YARA rule text generated by Claude.
    -- NULL if analysis_type = 'ttp_only'.
    draft_yara     TEXT,
    -- draft_ttp_map holds a JSON array of MITRE technique objects.
    -- NULL if analysis_type = 'yara_only'.
    draft_ttp_map  TEXT,
    -- pending_review → approved | rejected by an investigator.
    status         TEXT    NOT NULL DEFAULT 'pending_review'
                   CHECK (status IN ('pending_review', 'approved', 'rejected')),
    reviewer_notes TEXT,
    created_at     TEXT    NOT NULL,
    reviewed_at    TEXT
);

CREATE INDEX IF NOT EXISTS idx_draft_analysis_status
    ON draft_analysis (status);

CREATE INDEX IF NOT EXISTS idx_draft_analysis_raw_intel_id
    ON draft_analysis (raw_intel_id);
"""


def get_connection(timeout: int = 30) -> sqlite3.Connection:
    """
    Return a new sqlite3.Connection to DB_PATH.

    Each call creates a fresh connection. Callers are responsible for closing
    it (or using it as a context manager). row_factory is set to sqlite3.Row
    so columns are accessible by name.

    Args:
        timeout: Seconds to wait when the database is locked before raising
                 OperationalError. Default 30 suits Brain's long processing
                 windows; Bridge passes timeout=10 for fast interactive use.
    """
    with _lock:
        conn = sqlite3.connect(DB_PATH, timeout=timeout, check_same_thread=False)

    conn.row_factory = sqlite3.Row

    # Enable WAL mode: readers don't block writers and vice-versa.
    conn.execute("PRAGMA journal_mode=WAL;")
    # Enforce foreign-key constraints (draft_analysis → raw_intel).
    conn.execute("PRAGMA foreign_keys=ON;")

    return conn


def bootstrap_schema() -> None:
    """
    Create all tables and indexes if they do not exist.

    Also handles forward-migration of existing databases that predate the
    url_hash column: the column is added via ALTER TABLE if absent.

    Safe to call multiple times (all statements use IF NOT EXISTS).
    Called automatically when this module is imported.
    """
    with get_connection() as conn:
        # Create tables from scratch (no-op if they already exist).
        conn.executescript(_RAW_INTEL_DDL)
        conn.executescript(_DRAFT_ANALYSIS_DDL)

        # ── Forward migration: add url_hash to existing raw_intel rows ────
        existing_cols = {
            row[1]
            for row in conn.execute("PRAGMA table_info(raw_intel)")
        }
        if "url_hash" not in existing_cols:
            conn.execute("ALTER TABLE raw_intel ADD COLUMN url_hash TEXT")
            # Back-fill existing rows using the source_url as the hash input.
            # This keeps old data consistent without losing it.
            conn.execute(
                """
                UPDATE raw_intel
                SET url_hash = lower(hex(randomblob(32)))
                WHERE url_hash IS NULL
                """
            )
            # Note: we cannot retroactively set a UNIQUE constraint via ALTER
            # TABLE in SQLite. The CREATE INDEX above handles new databases.
            # For migrated databases, uniqueness is enforced by the index
            # added in _RAW_INTEL_DDL (IF NOT EXISTS is safe after the column add).

        conn.commit()


# ── Auto-bootstrap on import ──────────────────────────────────────────────────
bootstrap_schema()
